package com.example.domain.entity.data_model_movie_info


data class FilmInfo(
    var kinopoiskId: Int? = null,
    var kinopoiskHDId: String? = null,
    var imdbId: String? = null,
    var nameRu: String? = null,
    var nameEn: String? = null,
    var nameOriginal: String? = null,
    var posterUrl: String? = null,
    var posterUrlPreview: String? = null,
    var coverUrl: String? = null,
    var logoUrl: String? = null,
    var reviewsCount: Int? = null,
    var ratingGoodReview: Double? = null,
    var ratingGoodReviewVoteCount: Int? = null,
    var ratingKinopoisk: Double? = null,
    var ratingKinopoiskVoteCount: Int? = null,
    var ratingImdb: Double? = null,
    var ratingImdbVoteCount: Int? = null,
    var ratingFilmCritics: Double? = null,
    var ratingFilmCriticsVoteCount: Int? = null,
    var ratingAwait: Double? = null,
    var ratingAwaitCount: Int? = null,
    var ratingRfCritics: Double? = null,
    var ratingRfCriticsVoteCount: Int? = null,
    var webUrl: String? = null,
    var year: Int? = null,
    var filmLength: Int? = null,
    var slogan: String? = null,
    var description: String? = null,
    var shortDescription: String? = null,
    var editorAnnotation: String? = null,
    var isTicketsAvailable: Boolean? = null,
    var productionStatus: String? = null,
    var type: String? = null,
    var ratingMpaa: String? = null,
    var ratingAgeLimits: String? = null,
    var hasImax: Boolean? = null,
    var has3D: Boolean? = null,
    var lastSync: String? = null,
    var countries: List<Countries> = listOf(),
    var genres: List<Genres> = listOf(),
    var startYear: Int? = null,
    var endYear: Int? = null,
    var serial: Boolean? = null,
    var shortFilm: Boolean? = null,
    var completed: Boolean? = null
)